[tool.poetry]
name = "test1"
version = "0.1.0"
authors = ["Samuel Grayson <sam@samgrayson.me>"]
description = ""

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
